services:
  postgres-db:
    image: postgres:12.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  adiminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  app:
    build:
      context: .
    ports:
      - 5000:80
    depends_on: 
      - postgres-db
volumes:
  postgres-data: