apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet-kub-app
  template:
    metadata:
      labels:
        app: dotnet-kub-app
    spec:
      containers:
        - name: dotnet-kub-app
          image: billyao78/dotnet-kub-app-1:latest
          imagePullPolicy: Always